var mongoose = require('mongoose');
const { Schema } = mongoose;

const TestSchema = new Schema({
    type: { type: String, default: "tests"},

    _user: { type: Schema.Types.ObjectId, ref: 'User' },
    APresearch: Number,
    APseminar: Number,
    APmusic: Number,
    AParthistory: Number,
    APstudioart2d: Number,
    APstudioart3d: Number,
    APstudioartdrawing: Number,
    APenglishlanguage: Number,
    APenglishlit: Number,
    APcomparativegov: Number,
    APeuro: Number,
    APgeography: Number,
    APmacro: Number,
    APmicro: Number,
    APpsych: Number,
    APusgov: Number,
    APushistory: Number,
    APworldhistory: Number,
    APcalcAB: Number,
    APcalcBC: Number,
    APcompsciA: Number,
    APcompsciP: Number,
    APstat: Number,
    APbio: Number,
    APchem: Number,
    APenvironment: Number,
    APphysicsElect: Number,
    APphysicsMech: Number,
    APphysics1: Number,
    APphysics2: Number,
    APchinese: Number,
    APfrench: Number,
    APgerman: Number,
    APitalian: Number,
    APjapanese: Number,
    APlatin: Number,
    APspanishlang: Number,
    APspanishlit: Number,
    SAT: Number,
    SATmath: Number,
    SATenglish: Number,
    ACT: Number,
})

module.exports = mongoose.model('Tests',TestSchema);
